disabled_rules:
  - trailing_whitespace
  - vertical_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - FavotterTests
  - FavotterUITests
  - KuriTemplate
line_length:
  warning: 120 # only Warning